// <auto-generated />
namespace SwiftShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inventory_table_compareatprice_rename_cost_to_prica_in_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inventory_table_compareatprice_rename_cost_to_prica_in_product));
        
        string IMigrationMetadata.Id
        {
            get { return "201904130822137_inventory_table_compareatprice_rename_cost_to_prica_in_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
